---
- name: Install Docker on Debian
  block:
    - name: Install Docker and git
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: latest
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
  when: ansible_os_family == "Debian"

- name: Install Docker on Amazon
  block:
    - name: Install docker and git
      dnf:
        name:
          - docker
          - git
        state: latest
        update_cache: true

    - name: Remove python3-requests
      dnf:
        name: python3-requests
        state: absent

    - name: Ensure pip is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install Docker Compose from GitHub
      shell:
        cmd: "curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose"
      args:
        executable: /bin/bash


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
  when: ansible_os_family == "RedHat"

